export default {
  type: process.env.TYPEORM_CONNECTION,
  host: process.env.TYPEORM_HOST,
  port: Number(process.env.TYPEORM_PORT),
  username: process.env.TYPEORM_USERNAME,
  password: process.env.TYPEORM_PASSWORD,
  database: process.env.TYPEORM_DATABASE,
  entities: process.env.TYPEORM_ENTITIES?.split(','),
  entitiesDir: process.env.TYPEORM_ENTITIES_DIR,
  migrationsRun: process.env.DB_MIGRATIONS_RUN === 'true',
  migrations: process.env.TYPEORM_MIGRATIONS?.split(','),
  migrationsDir: process.env.DB_MIGRATIONS_DIR,
  logging: process.env.TYPEORM_LOGGING === 'true',
  synchronize: process.env.TYPEORM_SYNCHRONIZE === 'true',
  bigNumberStrings: false,
  timezone: 'Z',
};
